services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-azure-app_backend
    environment:
      - DATABASE=/app/db.sqlite3
    command: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
